
#include "ebox.h"

GPIO PA0(GPIOA,GPIO_Pin_0);
GPIO PA1(GPIOA,GPIO_Pin_1);
GPIO PA2(GPIOA,GPIO_Pin_2);
GPIO PA3(GPIOA,GPIO_Pin_3);
GPIO PA4(GPIOA,GPIO_Pin_4);
GPIO PA5(GPIOA,GPIO_Pin_5);
GPIO PA6(GPIOA,GPIO_Pin_6);
GPIO PA7(GPIOA,GPIO_Pin_7);
GPIO PA8(GPIOA,GPIO_Pin_8);
GPIO PA9(GPIOA,GPIO_Pin_9);
GPIO PA10(GPIOA,GPIO_Pin_10);
GPIO PA11(GPIOA,GPIO_Pin_11);
GPIO PA12(GPIOA,GPIO_Pin_12);
GPIO PA13(GPIOA,GPIO_Pin_13);
GPIO PA14(GPIOA,GPIO_Pin_14);
GPIO PA15(GPIOA,GPIO_Pin_15);

GPIO PB0(GPIOB,GPIO_Pin_0);
GPIO PB1(GPIOB,GPIO_Pin_1);
GPIO PB2(GPIOB,GPIO_Pin_2);
GPIO PB3(GPIOB,GPIO_Pin_3);
GPIO PB4(GPIOB,GPIO_Pin_4);
GPIO PB5(GPIOB,GPIO_Pin_5);
GPIO PB6(GPIOB,GPIO_Pin_6);
GPIO PB7(GPIOB,GPIO_Pin_7);
GPIO PB8(GPIOB,GPIO_Pin_8);
GPIO PB9(GPIOB,GPIO_Pin_9);
GPIO PB10(GPIOB,GPIO_Pin_10);
GPIO PB11(GPIOB,GPIO_Pin_11);
GPIO PB12(GPIOB,GPIO_Pin_12);
GPIO PB13(GPIOB,GPIO_Pin_13);
GPIO PB14(GPIOB,GPIO_Pin_14);
GPIO PB15(GPIOB,GPIO_Pin_15);


GPIO PE5(GPIOE,GPIO_Pin_5);
